// Hapanamy.lk Binary Volume Ledger & Matching Engine
const PlacementEngine = require('./placement-engine');

const VolumeLedger = {
    /**
     * Appends a new transaction entry into the binary volume ledger.
     */
    addEntry(ledger, userId, leg, amount, sourceUserId, sourcePurchaseId, type, beforeBalance) {
        const afterBalance = beforeBalance + amount;
        const entry = {
            id: 'ledger-uuid-' + Math.random().toString(36).substr(2, 9),
            user_id: userId,
            leg,
            amount,
            source_user_id: sourceUserId,
            source_purchase_id: sourcePurchaseId,
            type,
            before_balance: beforeBalance,
            after_balance: afterBalance,
            timestamp: new Date().toISOString()
        };
        ledger.push(entry);
        return entry;
    },

    /**
     * Calculates the active balance/volume for a user on a specific leg.
     */
    getLegBalance(userId, leg, ledger) {
        return ledger
            .filter(entry => entry.user_id === userId && entry.leg === leg)
            .reduce((sum, entry) => sum + entry.amount, 0.00);
    },

    /**
     * Propagates binary volume upwards along the binary tree path.
     * Enforces IDEMPOTENCY by checking if the sourcePurchaseId has already propagated.
     */
    propagateVolume(purchasingUserId, amount, sourcePurchaseId, binaryNodes, ledger) {
        // Idempotency check
        const alreadyPropagated = ledger.some(entry => entry.source_purchase_id === sourcePurchaseId && entry.type === 'SALE_VOLUME');
        if (alreadyPropagated) {
            console.log(`⚠️ Idempotency block: Purchase ${sourcePurchaseId} volume already propagated.`);
            return;
        }

        const node = binaryNodes.find(n => n.user_id === purchasingUserId);
        if (!node) return;

        let currentParentId = node.placement_parent_id;

        while (currentParentId) {
            // Determine side (LEFT or RIGHT) the purchasing user falls under for this parent
            const side = PlacementEngine.getLegUnderAncestor(purchasingUserId, currentParentId, binaryNodes);

            if (side) {
                const beforeBalance = this.getLegBalance(currentParentId, side, ledger);
                this.addEntry(ledger, currentParentId, side, amount, purchasingUserId, sourcePurchaseId, 'SALE_VOLUME', beforeBalance);
            }

            // Climb up
            const parentNode = binaryNodes.find(n => n.user_id === currentParentId);
            currentParentId = parentNode ? parentNode.placement_parent_id : null;
        }
    },

    /**
     * Performs binary matching logic and logs deduct matched entries.
     */
    matchVolume(userId, ledger) {
        const leftBalance = this.getLegBalance(userId, 'LEFT', ledger);
        const rightBalance = this.getLegBalance(userId, 'RIGHT', ledger);

        const matchedAmount = Math.min(leftBalance, rightBalance);
        if (matchedAmount <= 0.00) return null;

        // Log matched deductions in the ledger
        this.addEntry(ledger, userId, 'LEFT', -matchedAmount, userId, 'MATCH-SYSTEM', 'MATCHED_VOLUME', leftBalance);
        this.addEntry(ledger, userId, 'RIGHT', -matchedAmount, userId, 'MATCH-SYSTEM', 'MATCHED_VOLUME', rightBalance);

        return {
            userId,
            matchedAmount,
            leftCarryForward: leftBalance - matchedAmount,
            rightCarryForward: rightBalance - matchedAmount
        };
    },

    /**
     * Reverses binary volume generated by a refunded/cancelled purchase.
     */
    reverseVolume(sourcePurchaseId, binaryNodes, ledger) {
        const saleEntries = ledger.filter(entry => entry.source_purchase_id === sourcePurchaseId && entry.type === 'SALE_VOLUME');

        saleEntries.forEach(sale => {
            const currentBal = this.getLegBalance(sale.user_id, sale.leg, ledger);
            this.addEntry(ledger, sale.user_id, sale.leg, -sale.amount, sale.source_user_id, sourcePurchaseId, 'REVERSAL', currentBal);
        });
    }
};

if (typeof module !== 'undefined') {
    module.exports = VolumeLedger;
}
